Fix assemble

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -85,11 +85,26 @@ else
 echo "EXTRA_REPO ENCONTRADO - COMPILANDO REPOSITORIO ADICIONAL.."
 mkdir /opt/extra_repo && cd /opt/extra_repo && \
 git clone $EXTRA_REPO . && \
-mvn clean install -Dfile.encoding=UTF-8 -DskipTests=true ${MVN_OPTS_EXTRAREPO} && \
+mvn clean install -Dfile.encoding=UTF-8 -DskipTests=true ${MVN_OPTS_EXTRAREPO}
+
+ERR=$?
+    if [ $ERR -ne 0 ]; then
+	        echo "LA COMPILACION DE REPO EXTRA SALIO CON CODIGO DE ERROR $ERR"
+		    exit $ERR
+    fi
+
+
 echo "COMPILADO EXTRA_REPO FINALIZADO - LIMPIANDO DIRECTORIOS.." && rm -rf /opt/extra_repo 
 fi
 echo "---> COMPILANDO CODIGO FUENTE..."
-cd /opt/src && mvn clean package -Dfile.encoding=UTF-8 ${MVN_OPTS} && \
+cd /opt/src && mvn clean package -Dfile.encoding=UTF-8 ${MVN_OPTS}
+  
+ERR=$?
+    if [ $ERR -ne 0 ]; then
+	        echo "LA COMPILACION SALIO CON CODIGO DE ERROR $ERR"
+		    exit $ERR
+    fi
+
 echo "---> COPIANDO APLICACION GENERADA AL DIRECTORIO DE DEPLOY..."
 find . -name '*-thorntail.jar' | xargs cp -t . || find . -name '*-swarm.jar' | xargs cp -t . && mv *.jar /opt/app-root/app.jar && echo "APP INSTALADA!" && \
 rm -rf /opt/src /tmp/src /home/s2i/.m2
